### ISSUE TITLE
Support for Keycloak v21

### ISSUE THREAD

**Issue by cdecinkoKnight** [dsb-norge/vue-keycloak-js#171]
The latest version of dsb-norge/vue-keycloak-js uses keycloak-js v.18.0.1. We are now running Keycloak v.21. When can we expect this package to be updated to support v.21?

**Comment by chrisnruud** [comment]
Hi! The latest release should support v21 and be backwards compatible with v18, let us know if you find any issues with this. We have tested on our internal instances running v18 but since we don't have an environment running v21, we rely on outside testing to see if it works with the latest release.
