### ISSUE TITLE
Re-use config parameter names from the Keycloak adapter

### ISSUE THREAD

**Issue by anderius** [dsb-norge/vue-keycloak-js#8]
It is confusing to use `authRealm`, and not `realm`. We should probably find a way, without breaking backwards compatibility, to use the same names as Keycloak uses. And possibly simply pass the entire config objects info the adapter.

**Comment by anderius** [comment]
@acmore: I noticed your fork, is this something that would be useful for you?

**Comment by alfreema** [comment]
I agree with this.  Since keycloak generates a config for you like:

{
  "realm": "myrealm",
  "auth-server-url": "https://wherever.com/auth",
  "ssl-required": "external",
  "resource": "oidc",
  "public-client": true,
  "confidential-port": 0
}

it seems awkward to have to go in and change those and not allow that exact block to be pasted as a config to the adapter.  I would also vote that additional configs unique to the vue-keycloak-js plugin should be added outside that specific config block (such as logoutRedirectUri).

**Comment by alfreema** [comment]
Add the new ones and just make the old ones deprecated until 2.0.0?
